config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :show, :destroy, :update]
  resources :posts, only: [:index, :show] do
    resources :comments
  end

  namespace :admin do
    resources :posts, except: [:show] do
      collection do
        get :drafts, action: :index, status: :draft
        get :pending, action: :index, status: :pending
        get :reviewed, action: :index, status: :reviewed
        get :published, action: :index, status: :published
      end
      member do
        get :status_change
      end
    end
  end

  root 'posts#index'
  get '/about', to: 'pages#about'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  validates :name, :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  STATUS_TITLE = {
    "draft" => "Drafts",
    "pending" => "Waiting for review",
    "reviewed" => "Reviewed",
    "published" => "Published",
  }.freeze
  STATUSES = STATUS_TITLE.keys.freeze

  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true
  after_initialize :set_default_status, if:  :new_record?
  validates :status, inclusion: { in: STATUSES }

  scope :ordered, -> { order(created_at: :desc) }

  STATUSES.each do |status|
    scope status, -> { where(status: status) }
  end

  def author
    user.try(:email) || "Anonymous"
  end

  def set_default_status
    self.status ||= "draft"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  ROLES = %w[
    user
    admin
    writer
    editor
  ].freeze
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments, foreign_key: :user_id, dependent: :destroy
  has_many :posts

  validates :role, inclusion: { in: ROLES }

  after_initialize :set_default_role, if:  :new_record?

  def set_default_role
    self.role ||= "user"
  end

  def admin?
    self.role == "admin"
  end

  def writer?
    self.role == "writer"
  end

  def editor?
    self.role == "editor"
  end

  def not_admin?
    self.role != "admin"
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController
  def index
    status = params[:status].to_s
    @header = Post::STATUS_TITLE[status] || "All posts"
    if current_user.writer?
      @posts = current_user.posts.ordered
    elsif current_user.editor? || current_user.admin?
      @posts = Post.all.ordered
    else
      redirect_to root_path
    end
    @posts = @posts.send(status) if status.in? Post::STATUSES
  end

  def new
    @post = Post.new
    @submit_msg = "Create"
  end

  def create
    @post = current_user.posts.build(post_params)
    authorize @post
    if @post.save
      redirect_to @post
    else
      render "new"
    end
  end

  def edit
    @post = Post.find(params[:id])
    @submit_msg = "Edit"
  end

  def update
    @post = Post.find(params[:id])
    authorize @post
    if @post
      if @post.update(post_params)
        redirect_to @post
      else
        render "edit"
      end
    else
      render status: :forbidden, text: "Access denied!"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    authorize @post
    @post.destroy
    redirect_to root_path
  end

  def status_change
    @post = if current_user.writer?
              current_user.posts.find(params[:id])
            else
              Post.all.find(params[:id])
            end
    @post.status = params[:status]
    @post.save!
    redirect_to :back
  end

  private

  def post_params
    params[:post].permit(:title, :body)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  protect_from_forgery with: :exception

  private

  def user_not_authorized
    flash[:alert] = "Access denied."
    redirect_to request.referrer || root_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  def create
    post = Post.find(params[:post_id])
    comment = post.comments.build(params[:comment].permit(:name, :body))
    comment.user_id = current_user.id
    comment.name = comment.user.email
    if comment.save
      redirect_to post_path(post)
      flash[:success] = "Comment added."
    else
      redirect_to post_path(post)
      flash[:warning] = "Error"
    end
  end

  def destroy
    post = Post.find(params[:post_id])
    comment = post.comments.find(params[:id])
    comment.destroy
    redirect_to post_path(post)
    flash[:success] = "Comment deleted"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @header = "All Posts"
    @posts = Post.published.ordered
  end

  def show
    @post = Post.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show, :destroy]
  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(params[:user].permit(:role))
    redirect_to users_path
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    if user && current_user.role == "admin"
      user.destroy
      redirect_to users_path
    elsif user
      user.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end
end

app/helpers/admin/posts_helper.rb
module Admin
  module PostsHelper
    def link_to_change_status(post, status, &block)
      link_to status_change_admin_post_path(post, status: status),
        class: "btn btn-default",
        data: { confirm: "Are you sure?" },
        &block
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true,
      space_after_headers: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper

end

app/views/admin/posts/_form.html.erb
<%= form_for [:admin, @post] do |f| %>
  <% if @post.errors.any? %>
    <div class="errors">
      <h2>
        <%= pluralize(@post.errors.count, 'error') %> prevented this post from saving
      </h2>
      <ul>
        <% @post.errors.full_messages. each do |msg|%>
        <li><%= msg%></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field  :title, :class=>"form-control" %>
  </div>
    <div class="form-group" rows="20">
    <%= f.label :body %><br>
    <%= f.text_area :body, :class=>"form-control", :rows =>"25"%>
  </div>
  <%= f.submit "#{@submit_msg} #{@post.status.capitalize}"%>
<% end %>

app/views/admin/posts/_post_buttons.html.erb
<p>
  <%= link_to edit_admin_post_path(post), class: "btn btn-default" do %>
    <i class="glyphicon glyphicon-edit"> Edit</i>
  <% end %>
</p>
<p>
  <%= link_to admin_post_path(post),
                              class: "btn btn-default",
                              method: :delete,
                              data: {confirm: "Are you sure?"} do %>
    <i class="glyphicon glyphicon-remove"> Delete</i>
  <% end %>
</p>
<p>
  <% if post.status == "draft" && current_user.role == "writer" %>
    <%= link_to_change_status post, :pending do %>
      <i class="glyphicon glyphicon-share">Send to review</i>
    <% end %>
  <% end %>
  <% if post.status == "pending" && current_user.role == "editor" %>
    <%= link_to_change_status post, :reviewed do %>
      <i class="glyphicon glyphicon-share">Mark as reviewed</i>
    <% end %>
  <% end %>
  <% if post.status == "reviewed" && current_user.role == "editor"%>
    <%= link_to_change_status post, :published do %>
      <i class="glyphicon glyphicon-ok">Publish post</i>
    <% end %>
  <% end %>
</p>

app/views/admin/posts/edit.html.erb
<div class="page_wrapper">
  <h1>Edit post</h1>
  <%= render 'form' %>
</div>

app/views/admin/posts/index.html.erb
<h1><%= @header %></h1>
<% if @posts.length > 0 %>
  <table class="posts table table-bordered">
    <tr class="info">
      <th>Id</th>
      <th>Title</th>
      <th>Created</th>
      <th>Updated</th>
      <th>Actions</th>
    </tr>
    <% @posts.each do |post| %>
    <tr class="post">
      <td><%= post.id %></td>
      <td><%= link_to post.title, edit_admin_post_path(post) %></td>
      <td><%= post.created_at %></td>
      <td><%= post.updated_at %></td>
      <td>
        <%= render partial: "admin/posts/post_buttons", locals: { post: post} %>
      </td>
    </tr>
    <% end %>
  </table>
<% else %>
  <p>No posts found</p>
<% end %>

app/views/admin/posts/new.html.erb
<div class="page_wrapper">
<h1>New post</h1>
<%= render 'form' %>
</div>

app/views/comments/_comment.html.erb
<div class="comment">
  <p><%= comment.body %></p>
  <small>
    <%= time_ago_in_words(comment.created_at)%> ago by <%= comment.user.email %>
  </small>
  <% if user_signed_in? %>
  <br>
    <% if current_user.role == "admin" || current_user == comment.user %>
      <button type="button" class="btn btn-sm btn-danger del-comment">
        <%= link_to 'Delete', [comment.post, comment],
          method: :delete,
          class:'button',
          data: { confirm:'Are you shure?' } %>
      </button>
    <% end %>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build])  do |f| %>
  <p>
    <%= f.label :body %>
    <br>
    <%= f.text_area :body %>
  </p>
  <br>
  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/layouts/_editor_dropdown.html.erb
<li class="dropdown">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
    Editor menu
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
    <li><%= link_to "Waiting for review", pending_admin_posts_path %></li>
    <li><%= link_to "Reviewed", reviewed_admin_posts_path %></li>
    <li><%= link_to "Published", published_admin_posts_path %></li>
  </ul>
</li>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-default">
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header ">
      <div class="navbar-brand">CoopBlog</div>
      <% if current_page?(root_path) %>
      <% else %>
      <div class="navbar-brand">
        <%= link_to "Back to all posts", root_path %>
      </div>
      <% end %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <% if current_user.admin? %>
            <li><%= link_to "All Users", users_path %></li>
          <% end %>
          <% if current_user.admin? || current_user.writer? %>
            <%= render "layouts/writer_dropdown" %>
          <% end %>
          <% if current_user.admin? || current_user.editor? %>
            <%= render "layouts/editor_dropdown" %>
          <% end %>
          <li><%= link_to "Profile", user_path(current_user)%></li>
          <% if current_user.admin? || current_user.writer? %>
            <li><%= link_to 'New Post', new_admin_post_path %></li>
          <% end %>
            <li>
              <%= link_to 'Log Out', destroy_user_session_path, method: :delete %>
            </li>
        <% else %>
          <li><%= link_to 'Login',new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
</div>

app/views/layouts/_sidebar.html.erb
<div class="col-md-2 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
    <ul class="nav panel panel-default">
      <li class="panel-heading">Website</li>
      <li><%= link_to 'Blog', root_path %></li>
      <li><%= link_to 'About', about_path %></li>
      <li class="panel-heading">Social</li>
      <li><a href="https://www.instagram.com/fatpaher/">Instagram</a></li>
      <li><a href="https://twitter.com/FatPaher">Twitter</a></li>
      <li><a href="https://www.facebook.com/paul.pavlovsky.3">Facebook</a></li>
      <li><a href="mailto:fatpaher@gmail.com">Email</a></li>

    </ul>
</div>
<div class="nav-bar pull-left">

</div>

app/views/layouts/_writer_dropdown.html.erb
<li class="dropdown">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
    Writer menu
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
    <li><%= link_to "Drafts", drafts_admin_posts_path %></li>
    <li><%= link_to "Waiting for review", pending_admin_posts_path %></li>
    <li><%= link_to "Reviewed", reviewed_admin_posts_path %></li>
    <li><%= link_to "Published", published_admin_posts_path %></li>
  </ul>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  <%= render 'layouts/navbar' %>
    <div class="container">
     <div class="row">

     <%= render 'layouts/sidebar' %>
        <div class="col-md-10">
          <% flash.each do |name, msg| %>
            <%= content_tag(:div, msg, class: "alert") %>
          <% end %>
          <div class="main_content col-md-8">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Hey! It's about page</h1>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div class="errors">
      <h2>
        <%= pluralize(@post.errors.count, 'error') %> prevented this post from saving
      </h2>
      <ul>
        <% @post.errors.full_messages. each do |msg|%>
        <li><%= msg%></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field  :title, :class=>"form-control" %>
  </div>
    <div class="form-group">
    <%= f.label :body %><br>
    <%= f.text_area :body, :class=>"form-control"%>
  </div>
  <%= f.submit %>
<% end %>

app/views/posts/index.html.erb
<h1><%= @header %></h1>
<% @posts.each do |post| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>
          <%= link_to post.title, post %>
          <small class="pull-right"><%= post.created_at.strftime("%B, %d, %Y") %></small>
        </h3>
      </div>
      <div class="panel-body">
        <%= markdown post.body %>
      </div>
      <div class="panel-footer">
        <div class="btn btn-info">
          <%= link_to pluralize(post.comments.count, 'Comment'), post_path(post) %>
        </div>
      </div>
    </div>
<% end %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= form_for :post, url: posts_path do |f| %>
  <% if @post.errors.any? %>
    <div class="errors">
      <h2>
        <%= pluralize(@post.errors.count, 'error') %> prevented this post from saving
      </h2>
      <ul>
        <% @post.errors.full_messages. each do |msg|%>
        <li><%= msg%></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field  :title %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/show.html.erb
<div class="panel panel-default">
<div class="panel-heading"><h1 class="title"> <%= @post.title %></h1></div>
  <small>
    Submited <%= time_ago_in_words(@post.created_at) %> ago by <%= @post.author %>
  </small>
  <div class="panel-body">
    <p><%= markdown @post.body %></p>
  </div>
  <div class="panel-footer">
    <% if user_signed_in?  %>
      <% if current_user.role == "admin" || current_user == @post.user %>
        <button type="button" class="btn btn-sm">
          <%= link_to 'Edit', edit_admin_post_path(@post) %>
        </button>
        <button type="button" class="btn btn-sm">
          <%= link_to 'Delete', admin_post_path(@post),
                                method: :delete,
                                data: {confirm: 'Are you shure?'} %>
        </button>
      <% end %>
    <% end %>
  </div>
</div>

<div>
  <h3><%= pluralize(@post.comments.count, 'Comment')%></h3>
  <%= render @post.comments %>
  <% if user_signed_in? %>
    <h3>Add a comment</h3>
    <%= render 'comments/form' %>
  <% else %>
    <h3>You should sign in to leave a comment</h3>
  <% end %>
</div>

app/views/users/index.html.erb
<h1>All users</h1>
<table class="users table table bordered">
  <tr class="info">
    <th>User ID</th>
    <th>Email</th>
    <th>Role</th>
  </tr>
  <% @users.each do |user| %>
    <tr class="user-row">
      <td><%= link_to user.id, user_path(user) %></td>
      <td><%= link_to user.email, user_path(user) %></td>
        <td>
            <% if user != current_user %>
              <%= form_for user do |f| %>
              <%= f.select :role, User::ROLES  %>
              <%= f.submit "Change role" %>
            <% end %>
          <% end %>
        </td>
    </tr>
  <% end %>
</table>

app/views/users/show.html.erb
<div id="user_profile">
  <h1>Profile</h1>
  <%= @user.email %>
  <p>Status <%= @user.role %></p>
  <% if current_user.role == "user" || @user.role == "user" %>
    <%= link_to "Delete Profile", user_path(@user),
                                  method: :delete,
                                  data: {confirm: 'Are you shure?'} %>
  <% end %>
</div>